spring:
  application:
    name: graalvm
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=graalvm
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true